Update sync_fork.yml for improved sync process

diff --git a/.github/workflows/sync_fork.yml b/.github/workflows/sync_fork.yml
--- a/.github/workflows/sync_fork.yml
+++ b/.github/workflows/sync_fork.yml
@@ -1,9 +1,11 @@
 name: Fork Sync
 
+permissions:
+  contents: write
+
 on:
   schedule:
     - cron: '22 4 * * *'
-
   workflow_dispatch:
     inputs:
       sync_test_mode:
@@ -13,20 +15,28 @@ on:
 
 jobs:
   sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
     steps:
+      # Step 1: run a standard checkout action
       - name: Checkout target repo
         uses: actions/checkout@v6
-        with:
-          ref: main
-          persist-credentials: false
 
+      # Step 2: run the sync action
       - name: Sync upstream changes
-        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        id: sync
+        uses: aormsby/fork-sync-with-upstream-action@v3.4
         with:
-          target_sync_branch: main
-          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
-          upstream_sync_branch: main
           upstream_sync_repo: cmliu/edgetunnel
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
           test_mode: ${{ inputs.sync_test_mode }}
+
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次."
+          exit 1
